format:
    -alejandra **/*.nix

update:
    nix flake update
    if command -v darwin-rebuild; then darwin-rebuild switch --flake .; elif command -v nixos-rebuild; then sudo nixos-rebuild switch --flake .; fi
