theme = "catppuccin_latte"

# NOTE(nick): theme from the default set.
# theme = "onelight"

# NOTE(nick): add if using over ssh.
# [editor]
# true-color = true

# NOTE(nick): catppuccin recommendations
# [editor]
# line-number = "relative"
# cursorline = true
# color-modes = true

# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

# [editor.indent-guides]
# render = true
