[[language]]
name = "nix"
formatter = { command = "alejandra" }
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "markdown"
soft-wrap.enable = true

[[language]]
name = "sql"
auto-format = true

[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config.checkOnSave]
command = "check" # clippy works too
extraArgs = ["--target-dir", "target/rust-analyzer"]

[language-server.rust-analyzer.config.cargo]
allFeatures = true

[language-server.rust-analyzer.config.check]
command = "check" # clippy works too

# ==========================================================================================
# NOTE(nick): everything below this comment is absolute crazy town. Use at your own will.
# Source: https://github.com/helix-editor/helix/discussions/10691#discussioncomment-10688441
# ==========================================================================================

[[language]]
name = "vue"
auto-format = true
language-servers = ["vuels", "typescript-language-server"]
formatter = { command = 'prettier', args = ["--parser", "vue"] }

[language-server.vuels]
command = "vue-language-server"
args = ["--stdio"]

[language-server.typescript-language-server]
filetypes = ["javascript", "typescript"]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.typescript-language-server.config]
plugins = [{  name = "@vue/typescript-plugin", location = "../../.npm-global/lib/node_modules/@vue/language-server", languages = ["vue"] }]
tsserver = { path = "../../.npm-global/lib/node_modules/typescript/lib" }

[language-server.typescript-language-server.config.vue.inlayHints]
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "all"
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true
