[[language]]
name = "nix"
formatter = { command = "nixpkgs-fmt" }
auto-format = true

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "markdown"
soft-wrap.enable = true

[language-server.rust-analyzer.config.checkOnSave]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
allFeatures = true

[language-server.rust-analyzer.config.check]
command = "clippy"
