name: "Flake Health Check"
on:
  pull_request:
  push:
jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Flake.lock health check"
      shell: bash
      run: |
        (
          set -eu
          curl --max-time 2 --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/flake-checker/stable/$RUNNER_ARCH-$RUNNER_OS > "$RUNNER_TEMP/flake-checker"
          chmod +x "$RUNNER_TEMP/flake-checker"
          "$RUNNER_TEMP/flake-checker"
        ) || true
